//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsItem
    {
        public int NewsItemID { get; set; }
        public string Title { get; set; }
        public string UrlTitle { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public string Author { get; set; }
        public string Summary { get; set; }
        public string Body { get; set; }
        public Nullable<double> LocatorPositionX { get; set; }
        public Nullable<double> LocatorPositionY { get; set; }
        public string LocationPopupTitle { get; set; }
        public string LocationPopupDescription { get; set; }
        public bool IsDeleted { get; set; }
    }
}
